<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('users', function (Blueprint $table) {
            $table->id();
            $table->string('name', 150)->comment('User full name');
            $table->string('email', 190)->unique()->comment('User email address');
            $table->string('phone', 30)->nullable()->comment('User phone number');
            $table->string('password', 255)->comment('Hashed password');
            $table->string('role', 30)->default('customer')->comment('admin, staff, customer');
            $table->string('status', 30)->default('active')->comment('active, suspended, banned');
            $table->string('avatar', 255)->nullable()->comment('User profile image');
            $table->timestamp('last_login_at')->nullable()->comment('Last login time');
            $table->timestamp('email_verified_at')->nullable()->comment('Email verification time');
            $table->text('notes')->nullable()->comment('Private admin note about this user');
            $table->rememberToken();
            $table->timestamps();
            $table->softDeletes();
            $table->index('role', 'idx_users_role');
            $table->index('status', 'idx_users_status');
            $table->index('phone', 'idx_users_phone');
            $table->comment('Stores admins, staff, and customers');
        });

        Schema::create('tool_categories', function (Blueprint $table) {
            $table->id();
            $table->string('name', 150)->comment('Category name, for example SEO Tools');
            $table->string('slug', 190)->unique()->comment('URL-friendly category name');
            $table->text('description')->nullable()->comment('Category description');
            $table->string('status', 30)->default('active')->comment('active, inactive');
            $table->unsignedInteger('sort_order')->default(0)->comment('Display order');
            $table->timestamps();
            $table->softDeletes();
            $table->index('status', 'idx_tool_categories_status');
            $table->comment('Stores categories for tools');
        });

        Schema::create('tools', function (Blueprint $table) {
            $table->id();
            $table->foreignId('category_id')->nullable()->constrained('tool_categories')->nullOnDelete();
            $table->string('name', 150)->comment('Tool name, for example ChatGPT or Ahrefs');
            $table->string('slug', 190)->unique()->comment('URL-friendly tool name');
            $table->string('website_url', 255)->nullable()->comment('Official website URL');
            $table->string('logo', 255)->nullable()->comment('Tool logo image path');
            $table->text('description')->nullable()->comment('Tool description');
            $table->string('status', 30)->default('active')->comment('active, inactive');
            $table->string('access_type', 50)->default('credential')->comment('credential, invite, instruction, manual, external');
            $table->boolean('otp_required')->default(false)->comment('1 means this tool may require OTP or 2FA during login');
            $table->string('otp_type', 50)->nullable()->comment('email, sms, authenticator, backup_code, device_approval, manual');
            $table->text('otp_note')->nullable()->comment('Admin/customer note about OTP or 2FA process');
            $table->boolean('device_restriction_enabled')->default(false)->comment('1 means this tool has device/session/IP restrictions');
            $table->string('device_limit_type', 50)->nullable()->comment('device, browser, session, ip, simultaneous_user, none');
            $table->unsignedInteger('default_max_devices')->nullable()->comment('Default allowed devices/sessions for this tool');
            $table->text('device_policy_note')->nullable()->comment('Customer/admin note about device restrictions');
            $table->timestamps();
            $table->softDeletes();
            $table->index('category_id', 'idx_tools_category_id');
            $table->index('status', 'idx_tools_status');
            $table->index('access_type', 'idx_tools_access_type');
            $table->index('otp_required', 'idx_tools_otp_required');
            $table->index('device_restriction_enabled', 'idx_tools_device_restriction_enabled');
            $table->comment('Stores tools/software that can be sold individually or inside bundles');
        });

        Schema::create('tool_accounts', function (Blueprint $table) {
            $table->id();
            $table->foreignId('tool_id')->constrained('tools')->cascadeOnDelete();
            $table->string('name', 150)->comment('Internal account name, for example ChatGPT Pro Account 1');
            $table->string('login_email', 190)->nullable()->comment('Login email if credential-based access is used');
            $table->text('login_password_encrypted')->nullable()->comment('Encrypted password, never plain text');
            $table->string('recovery_email', 190)->nullable()->comment('Recovery email');
            $table->string('account_url', 255)->nullable()->comment('Login or dashboard URL');
            $table->string('subscription_type', 50)->default('monthly')->comment('monthly, yearly, lifetime, trial');
            $table->decimal('purchase_price', 12, 2)->default(0.00)->comment('Original purchase cost');
            $table->decimal('renewal_price', 12, 2)->default(0.00)->comment('Renewal cost');
            $table->date('purchase_date')->nullable()->comment('Purchase date');
            $table->date('renewal_date')->nullable()->comment('Next renewal date');
            $table->date('expires_at')->nullable()->comment('Subscription expiry date');
            $table->unsignedInteger('max_users')->default(1)->comment('Maximum customers allowed for this account');
            $table->unsignedInteger('used_slots')->default(0)->comment('Currently assigned customers');
            $table->boolean('device_restriction_enabled')->default(false)->comment('1 means this account has device/session/IP restrictions');
            $table->unsignedInteger('max_devices')->nullable()->comment('Maximum allowed devices/sessions/IPs for this account');
            $table->unsignedInteger('used_devices')->default(0)->comment('Currently registered/used devices');
            $table->string('device_limit_type', 50)->nullable()->comment('device, browser, session, ip, simultaneous_user, none');
            $table->boolean('allow_device_reset')->default(true)->comment('1 means admin can reset/remove devices');
            $table->unsignedInteger('device_reset_interval_days')->nullable()->comment('Minimum days before customer can request device reset again');
            $table->text('device_policy_note')->nullable()->comment('Admin/customer note about account device policy');
            $table->boolean('otp_required')->default(false)->comment('1 means this account requires OTP/2FA');
            $table->string('otp_type', 50)->nullable()->comment('email, sms, authenticator, backup_code, device_approval, manual');
            $table->string('otp_receiver', 190)->nullable()->comment('Where OTP is received, for example owner email or phone');
            $table->text('otp_note')->nullable()->comment('Private admin note about how to handle OTP/2FA');
            $table->text('two_factor_secret_encrypted')->nullable()->comment('Encrypted 2FA secret if owner decides to store it');
            $table->text('backup_codes_encrypted')->nullable()->comment('Encrypted backup codes if used');
            $table->string('status', 30)->default('active')->comment('active, expired, full, disabled, issue');
            $table->timestamp('last_checked_at')->nullable()->comment('Last admin check time');
            $table->timestamp('last_issue_at')->nullable()->comment('Last issue report time');
            $table->text('issue_note')->nullable()->comment('Issue note if account has problem');
            $table->text('notes')->nullable()->comment('Private admin note');
            $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();
            $table->foreignId('updated_by')->nullable()->constrained('users')->nullOnDelete();
            $table->timestamps();
            $table->softDeletes();
            $table->index('tool_id', 'idx_tool_accounts_tool_id');
            $table->index('status', 'idx_tool_accounts_status');
            $table->index('renewal_date', 'idx_tool_accounts_renewal_date');
            $table->index('expires_at', 'idx_tool_accounts_expires_at');
            $table->index('otp_required', 'idx_tool_accounts_otp_required');
            $table->index('device_restriction_enabled', 'idx_tool_accounts_device_restriction_enabled');
            $table->comment('Stores owned tool subscriptions/accounts/licenses');
        });

        Schema::create('packages', function (Blueprint $table) {
            $table->id();
            $table->string('name', 150)->comment('Package name shown to customer');
            $table->string('slug', 190)->unique()->comment('URL-friendly package name');
            $table->string('type', 30)->default('single')->comment('single, bundle');
            $table->string('delivery_type', 50)->default('auto')->comment('auto, manual, mixed');
            $table->text('description')->nullable()->comment('Package description');
            $table->decimal('price', 12, 2)->default(0.00)->comment('Selling price');
            $table->unsignedInteger('duration_days')->default(30)->comment('Access duration in days');
            $table->string('status', 30)->default('active')->comment('active, inactive');
            $table->unsignedInteger('sort_order')->default(0)->comment('Display order');
            $table->boolean('is_featured')->default(false)->comment('1 means featured package');
            $table->timestamps();
            $table->softDeletes();
            $table->index('type', 'idx_packages_type');
            $table->index('delivery_type', 'idx_packages_delivery_type');
            $table->index('status', 'idx_packages_status');
            $table->index('price', 'idx_packages_price');
            $table->comment('Stores sellable single-tool or multi-tool bundle packages');
        });

        Schema::create('package_tools', function (Blueprint $table) {
            $table->id();
            $table->foreignId('package_id')->constrained('packages')->cascadeOnDelete();
            $table->foreignId('tool_id')->constrained('tools')->cascadeOnDelete();
            $table->timestamps();
            $table->unique(['package_id', 'tool_id'], 'uq_package_tool');
            $table->index('package_id', 'idx_package_tools_package_id');
            $table->index('tool_id', 'idx_package_tools_tool_id');
            $table->comment('Stores tools included in each package');
        });

        Schema::create('package_custom_fields', function (Blueprint $table) {
            $table->id();
            $table->foreignId('package_id')->constrained('packages')->cascadeOnDelete();
            $table->string('label', 150)->comment('Field label shown to customer');
            $table->string('name', 150)->comment('Machine field name, for example invite_email');
            $table->string('type', 50)->default('text')->comment('text, email, number, textarea, url, select, checkbox, radio, date, file');
            $table->string('placeholder', 255)->nullable()->comment('Input placeholder text');
            $table->text('help_text')->nullable()->comment('Help text shown below field');
            $table->json('options')->nullable()->comment('Options for select, checkbox, or radio fields');
            $table->boolean('is_required')->default(false)->comment('1 means customer must fill this field');
            $table->string('validation_rules', 255)->nullable()->comment('Laravel validation rules, for example required|email');
            $table->unsignedInteger('sort_order')->default(0)->comment('Field display order');
            $table->string('status', 30)->default('active')->comment('active, inactive');
            $table->timestamps();
            $table->softDeletes();
            $table->unique(['package_id', 'name'], 'uq_package_custom_field_name');
            $table->index('package_id', 'idx_package_custom_fields_package_id');
            $table->index('type', 'idx_package_custom_fields_type');
            $table->index('status', 'idx_package_custom_fields_status');
            $table->comment('Stores custom customer information fields required for packages');
        });

        Schema::create('orders', function (Blueprint $table) {
            $table->id();
            $table->foreignId('user_id')->constrained('users')->cascadeOnDelete();
            $table->foreignId('package_id')->constrained('packages')->restrictOnDelete();
            $table->string('order_number', 50)->unique()->comment('Public order number, for example ORD-10001');
            $table->decimal('amount', 12, 2)->default(0.00)->comment('Original package amount');
            $table->decimal('discount_amount', 12, 2)->default(0.00)->comment('Discount amount');
            $table->decimal('payable_amount', 12, 2)->default(0.00)->comment('Final payable amount');
            $table->string('payment_method', 50)->nullable()->comment('bkash, nagad, rocket, bank, manual, card');
            $table->string('payment_status', 30)->default('pending')->comment('pending, paid, failed, refunded');
            $table->string('order_status', 30)->default('pending')->comment('pending, active, expired, cancelled');
            $table->string('required_info_status', 30)->default('not_required')->comment('not_required, pending, submitted, approved, rejected');
            $table->timestamp('required_info_submitted_at')->nullable()->comment('When customer submitted required information');
            $table->foreignId('required_info_reviewed_by')->nullable()->constrained('users')->nullOnDelete();
            $table->timestamp('required_info_reviewed_at')->nullable()->comment('When required information was reviewed');
            $table->text('required_info_reject_reason')->nullable()->comment('Reason if required information was rejected');
            $table->timestamp('starts_at')->nullable()->comment('Order/access start time');
            $table->timestamp('expires_at')->nullable()->comment('Order/access expiry time');
            $table->foreignId('renewed_from_order_id')->nullable()->constrained('orders')->nullOnDelete();
            $table->text('customer_note')->nullable()->comment('Customer note');
            $table->text('admin_note')->nullable()->comment('Private admin note');
            $table->timestamps();
            $table->softDeletes();
            $table->index('user_id', 'idx_orders_user_id');
            $table->index('package_id', 'idx_orders_package_id');
            $table->index('payment_status', 'idx_orders_payment_status');
            $table->index('order_status', 'idx_orders_order_status');
            $table->index('required_info_status', 'idx_orders_required_info_status');
            $table->index('expires_at', 'idx_orders_expires_at');
            $table->comment('Stores customer orders and required information review status');
        });

        Schema::create('order_custom_field_values', function (Blueprint $table) {
            $table->id();
            $table->foreignId('order_id')->constrained('orders')->cascadeOnDelete();
            $table->foreignId('package_custom_field_id')->constrained('package_custom_fields')->cascadeOnDelete();
            $table->string('field_name', 150)->comment('Copied field name for history/easier lookup');
            $table->string('field_label', 150)->comment('Copied field label for history');
            $table->text('value')->nullable()->comment('Customer submitted value');
            $table->string('file_path', 255)->nullable()->comment('Uploaded file path if field type is file');
            $table->timestamps();
            $table->softDeletes();
            $table->unique(['order_id', 'package_custom_field_id'], 'uq_order_custom_field_value');
            $table->index('order_id', 'idx_order_custom_field_values_order_id');
            $table->index('package_custom_field_id', 'idx_order_custom_field_values_field_id');
            $table->index('field_name', 'idx_order_custom_field_values_field_name');
            $table->comment('Stores customer submitted answers for package custom fields');
        });

        Schema::create('payments', function (Blueprint $table) {
            $table->id();
            $table->foreignId('order_id')->constrained('orders')->cascadeOnDelete();
            $table->foreignId('user_id')->constrained('users')->cascadeOnDelete();
            $table->decimal('amount', 12, 2)->default(0.00)->comment('Paid amount');
            $table->string('method', 50)->comment('bkash, nagad, rocket, bank, manual, card');
            $table->string('transaction_id', 100)->nullable()->comment('Payment transaction ID');
            $table->string('sender_number', 50)->nullable()->comment('Sender mobile number');
            $table->string('screenshot', 255)->nullable()->comment('Payment screenshot path');
            $table->string('status', 30)->default('pending')->comment('pending, verified, rejected');
            $table->foreignId('verified_by')->nullable()->constrained('users')->nullOnDelete();
            $table->timestamp('verified_at')->nullable()->comment('Payment verification time');
            $table->text('reject_reason')->nullable()->comment('Reason if payment rejected');
            $table->text('note')->nullable()->comment('Private payment note');
            $table->timestamps();
            $table->softDeletes();
            $table->index('order_id', 'idx_payments_order_id');
            $table->index('user_id', 'idx_payments_user_id');
            $table->index('status', 'idx_payments_status');
            $table->index('method', 'idx_payments_method');
            $table->index('transaction_id', 'idx_payments_transaction_id');
            $table->comment('Stores customer payment records and verification status');
        });

        Schema::create('user_tool_accesses', function (Blueprint $table) {
            $table->id();
            $table->foreignId('user_id')->constrained('users')->cascadeOnDelete();
            $table->foreignId('order_id')->nullable()->constrained('orders')->nullOnDelete();
            $table->foreignId('tool_id')->constrained('tools')->cascadeOnDelete();
            $table->foreignId('tool_account_id')->nullable()->constrained('tool_accounts')->nullOnDelete();
            $table->string('source', 30)->default('order')->comment('order, manual, bonus, replacement, trial');
            $table->string('status', 30)->default('active')->comment('active, expired, suspended, revoked');
            $table->string('delivery_status', 50)->default('pending')->comment('pending, processing, delivered, failed, cancelled');
            $table->string('customer_email_for_invite', 190)->nullable()->comment('Email admin should invite for invite-only tools');
            $table->timestamp('starts_at')->nullable()->comment('Access start time');
            $table->timestamp('expires_at')->nullable()->comment('Access expiry time');
            $table->timestamp('invited_at')->nullable()->comment('When admin sent invite');
            $table->timestamp('delivered_at')->nullable()->comment('When access was delivered');
            $table->text('access_note')->nullable()->comment('Instruction shown to customer');
            $table->text('delivery_note')->nullable()->comment('Customer/admin-facing delivery note');
            $table->text('internal_note')->nullable()->comment('Private admin note');
            $table->timestamp('last_accessed_at')->nullable()->comment('Last time customer viewed/opened this access');
            $table->timestamp('revoked_at')->nullable()->comment('When access was revoked');
            $table->foreignId('revoked_by')->nullable()->constrained('users')->nullOnDelete();
            $table->text('revoked_reason')->nullable()->comment('Reason for revoking access');
            $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();
            $table->foreignId('updated_by')->nullable()->constrained('users')->nullOnDelete();
            $table->timestamps();
            $table->softDeletes();
            $table->index('user_id', 'idx_user_tool_accesses_user_id');
            $table->index('order_id', 'idx_user_tool_accesses_order_id');
            $table->index('tool_id', 'idx_user_tool_accesses_tool_id');
            $table->index('tool_account_id', 'idx_user_tool_accesses_tool_account_id');
            $table->index('source', 'idx_user_tool_accesses_source');
            $table->index('status', 'idx_user_tool_accesses_status');
            $table->index('delivery_status', 'idx_user_tool_accesses_delivery_status');
            $table->index('expires_at', 'idx_user_tool_accesses_expires_at');
            $table->comment('Stores customer access to tools/accounts including manual and invite-only delivery');
        });

        Schema::create('user_tool_devices', function (Blueprint $table) {
            $table->id();
            $table->foreignId('user_id')->constrained('users')->cascadeOnDelete();
            $table->foreignId('user_tool_access_id')->constrained('user_tool_accesses')->cascadeOnDelete();
            $table->foreignId('tool_id')->constrained('tools')->cascadeOnDelete();
            $table->foreignId('tool_account_id')->nullable()->constrained('tool_accounts')->nullOnDelete();
            $table->string('device_name', 150)->nullable()->comment('Customer/admin friendly device name');
            $table->string('device_type', 50)->nullable()->comment('desktop, laptop, mobile, tablet, browser, unknown');
            $table->string('browser_name', 100)->nullable()->comment('Browser name if known');
            $table->string('operating_system', 100)->nullable()->comment('Operating system if known');
            $table->string('ip_address', 45)->nullable()->comment('Last known IP address');
            $table->text('user_agent')->nullable()->comment('Browser/device user agent');
            $table->string('device_fingerprint', 190)->nullable()->comment('Optional device/browser fingerprint hash');
            $table->string('status', 30)->default('active')->comment('active, pending_approval, blocked, removed, expired');
            $table->foreignId('approved_by')->nullable()->constrained('users')->nullOnDelete();
            $table->timestamp('approved_at')->nullable()->comment('When device was approved');
            $table->timestamp('first_used_at')->nullable()->comment('First time this device was used/registered');
            $table->timestamp('last_used_at')->nullable()->comment('Last time this device was used');
            $table->foreignId('removed_by')->nullable()->constrained('users')->nullOnDelete();
            $table->timestamp('removed_at')->nullable()->comment('When device was removed');
            $table->text('remove_reason')->nullable()->comment('Reason for removing/blocking device');
            $table->text('note')->nullable()->comment('Private admin note');
            $table->timestamps();
            $table->softDeletes();
            $table->index('user_id', 'idx_user_tool_devices_user_id');
            $table->index('user_tool_access_id', 'idx_user_tool_devices_access_id');
            $table->index('tool_id', 'idx_user_tool_devices_tool_id');
            $table->index('tool_account_id', 'idx_user_tool_devices_tool_account_id');
            $table->index('status', 'idx_user_tool_devices_status');
            $table->index('device_fingerprint', 'idx_user_tool_devices_fingerprint');
            $table->index('ip_address', 'idx_user_tool_devices_ip_address');
            $table->comment('Tracks customer devices/sessions/IPs used for tool access');
        });

        Schema::create('device_reset_requests', function (Blueprint $table) {
            $table->id();
            $table->foreignId('user_id')->constrained('users')->cascadeOnDelete();
            $table->foreignId('user_tool_access_id')->constrained('user_tool_accesses')->cascadeOnDelete();
            $table->foreignId('tool_id')->constrained('tools')->cascadeOnDelete();
            $table->foreignId('tool_account_id')->nullable()->constrained('tool_accounts')->nullOnDelete();
            $table->foreignId('old_device_id')->nullable()->constrained('user_tool_devices')->nullOnDelete();
            $table->string('status', 30)->default('pending')->comment('pending, processing, approved, rejected, cancelled');
            $table->text('customer_reason')->nullable()->comment('Customer reason for reset request');
            $table->text('admin_note')->nullable()->comment('Private admin note');
            $table->foreignId('reviewed_by')->nullable()->constrained('users')->nullOnDelete();
            $table->timestamp('reviewed_at')->nullable()->comment('When request was reviewed');
            $table->text('reject_reason')->nullable()->comment('Reason if rejected');
            $table->timestamp('completed_at')->nullable()->comment('When device reset was completed');
            $table->timestamps();
            $table->softDeletes();
            $table->index('user_id', 'idx_device_reset_requests_user_id');
            $table->index('user_tool_access_id', 'idx_device_reset_requests_access_id');
            $table->index('tool_id', 'idx_device_reset_requests_tool_id');
            $table->index('tool_account_id', 'idx_device_reset_requests_tool_account_id');
            $table->index('old_device_id', 'idx_device_reset_requests_old_device_id');
            $table->index('status', 'idx_device_reset_requests_status');
            $table->comment('Stores customer device reset/change requests');
        });

        Schema::create('otp_requests', function (Blueprint $table) {
            $table->id();
            $table->foreignId('user_id')->constrained('users')->cascadeOnDelete();
            $table->foreignId('order_id')->nullable()->constrained('orders')->nullOnDelete();
            $table->foreignId('user_tool_access_id')->constrained('user_tool_accesses')->cascadeOnDelete();
            $table->foreignId('tool_id')->constrained('tools')->cascadeOnDelete();
            $table->foreignId('tool_account_id')->nullable()->constrained('tool_accounts')->nullOnDelete();
            $table->string('request_type', 50)->default('email_otp')->comment('email_otp, sms_otp, authenticator_2fa, backup_code, device_approval, manual');
            $table->string('status', 30)->default('pending')->comment('pending, processing, provided, used, expired, rejected, cancelled, revoked');
            $table->text('customer_message')->nullable()->comment('Message from customer');
            $table->text('admin_note')->nullable()->comment('Private admin note');
            $table->text('otp_code_encrypted')->nullable()->comment('Encrypted OTP/2FA code entered by admin');
            $table->timestamp('otp_expires_at')->nullable()->comment('When this OTP/code expires');
            $table->timestamp('requested_for_at')->nullable()->comment('Customer requested OTP for this login time or attempt');
            $table->foreignId('provided_by')->nullable()->constrained('users')->nullOnDelete();
            $table->timestamp('provided_at')->nullable()->comment('When OTP/code was provided');
            $table->timestamp('used_at')->nullable()->comment('When customer marked OTP as used');
            $table->foreignId('rejected_by')->nullable()->constrained('users')->nullOnDelete();
            $table->timestamp('rejected_at')->nullable()->comment('When request was rejected');
            $table->text('reject_reason')->nullable()->comment('Reason for rejection');
            $table->foreignId('cancelled_by')->nullable()->constrained('users')->nullOnDelete();
            $table->timestamp('cancelled_at')->nullable()->comment('When request was cancelled');
            $table->text('cancel_reason')->nullable()->comment('Reason for cancellation');
            $table->foreignId('revoked_by')->nullable()->constrained('users')->nullOnDelete();
            $table->timestamp('revoked_at')->nullable()->comment('When OTP request was revoked');
            $table->text('revoke_reason')->nullable()->comment('Reason for revoking this OTP request');
            $table->timestamps();
            $table->softDeletes();
            $table->index('user_id', 'idx_otp_requests_user_id');
            $table->index('order_id', 'idx_otp_requests_order_id');
            $table->index('user_tool_access_id', 'idx_otp_requests_access_id');
            $table->index('tool_id', 'idx_otp_requests_tool_id');
            $table->index('tool_account_id', 'idx_otp_requests_tool_account_id');
            $table->index('request_type', 'idx_otp_requests_request_type');
            $table->index('status', 'idx_otp_requests_status');
            $table->index('otp_expires_at', 'idx_otp_requests_otp_expires_at');
            $table->index('requested_for_at', 'idx_otp_requests_requested_for_at');
            $table->comment('Stores customer OTP/2FA requests for tool login verification');
        });

        Schema::create('admin_tasks', function (Blueprint $table) {
            $table->id();
            $table->foreignId('user_id')->nullable()->constrained('users')->nullOnDelete();
            $table->foreignId('order_id')->nullable()->constrained('orders')->nullOnDelete();
            $table->foreignId('user_tool_access_id')->nullable()->constrained('user_tool_accesses')->nullOnDelete();
            $table->foreignId('otp_request_id')->nullable()->constrained('otp_requests')->nullOnDelete();
            $table->foreignId('device_reset_request_id')->nullable()->constrained('device_reset_requests')->nullOnDelete();
            $table->string('title', 255)->comment('Task title');
            $table->text('description')->nullable()->comment('Task details');
            $table->string('type', 50)->default('manual_delivery')->comment('manual_delivery, invite_user, verify_payment, renewal, support, review_required_info, provide_otp, provide_2fa, approve_device, device_reset');
            $table->string('priority', 30)->default('medium')->comment('low, medium, high, urgent');
            $table->string('status', 30)->default('pending')->comment('pending, processing, completed, cancelled');
            $table->foreignId('assigned_to')->nullable()->constrained('users')->nullOnDelete();
            $table->timestamp('due_at')->nullable()->comment('Task due time');
            $table->timestamp('completed_at')->nullable()->comment('Task completion time');
            $table->timestamps();
            $table->softDeletes();
            $table->index('user_id', 'idx_admin_tasks_user_id');
            $table->index('order_id', 'idx_admin_tasks_order_id');
            $table->index('user_tool_access_id', 'idx_admin_tasks_access_id');
            $table->index('otp_request_id', 'idx_admin_tasks_otp_request_id');
            $table->index('device_reset_request_id', 'idx_admin_tasks_device_reset_request_id');
            $table->index('type', 'idx_admin_tasks_type');
            $table->index('status', 'idx_admin_tasks_status');
            $table->index('priority', 'idx_admin_tasks_priority');
            $table->index('assigned_to', 'idx_admin_tasks_assigned_to');
            $table->comment('Stores manual admin tasks such as invite delivery, OTP, device reset, and info review');
        });

        Schema::create('support_tickets', function (Blueprint $table) {
            $table->id();
            $table->foreignId('user_id')->constrained('users')->cascadeOnDelete();
            $table->foreignId('order_id')->nullable()->constrained('orders')->nullOnDelete();
            $table->foreignId('tool_id')->nullable()->constrained('tools')->nullOnDelete();
            $table->foreignId('tool_account_id')->nullable()->constrained('tool_accounts')->nullOnDelete();
            $table->foreignId('user_tool_access_id')->nullable()->constrained('user_tool_accesses')->nullOnDelete();
            $table->string('ticket_number', 50)->unique()->comment('Public ticket number, for example TKT-10001');
            $table->string('subject', 255)->comment('Ticket subject');
            $table->string('category', 50)->default('other')->comment('login_issue, payment_issue, renewal, technical, delivery_issue, otp_issue, device_issue, other');
            $table->string('priority', 30)->default('medium')->comment('low, medium, high, urgent');
            $table->string('status', 30)->default('open')->comment('open, pending, solved, closed');
            $table->foreignId('assigned_to')->nullable()->constrained('users')->nullOnDelete();
            $table->timestamp('last_reply_at')->nullable()->comment('Last reply time');
            $table->timestamp('closed_at')->nullable()->comment('Ticket closing time');
            $table->timestamps();
            $table->softDeletes();
            $table->index('user_id', 'idx_support_tickets_user_id');
            $table->index('order_id', 'idx_support_tickets_order_id');
            $table->index('tool_id', 'idx_support_tickets_tool_id');
            $table->index('tool_account_id', 'idx_support_tickets_tool_account_id');
            $table->index('user_tool_access_id', 'idx_support_tickets_access_id');
            $table->index('status', 'idx_support_tickets_status');
            $table->index('priority', 'idx_support_tickets_priority');
            $table->index('assigned_to', 'idx_support_tickets_assigned_to');
            $table->comment('Stores customer support tickets');
        });

        Schema::create('support_ticket_messages', function (Blueprint $table) {
            $table->id();
            $table->foreignId('ticket_id')->constrained('support_tickets')->cascadeOnDelete();
            $table->foreignId('sender_id')->constrained('users')->cascadeOnDelete();
            $table->text('message')->comment('Message body');
            $table->string('attachment', 255)->nullable()->comment('Attachment path');
            $table->boolean('is_staff_reply')->default(false)->comment('1 if reply is from admin/staff');
            $table->timestamps();
            $table->softDeletes();
            $table->index('ticket_id', 'idx_support_ticket_messages_ticket_id');
            $table->index('sender_id', 'idx_support_ticket_messages_sender_id');
            $table->comment('Stores messages inside support tickets');
        });

        Schema::create('announcements', function (Blueprint $table) {
            $table->id();
            $table->string('title', 255)->comment('Announcement title');
            $table->text('message')->comment('Announcement message');
            $table->string('type', 30)->default('info')->comment('info, warning, maintenance, success');
            $table->string('status', 30)->default('active')->comment('active, inactive');
            $table->string('visible_to', 30)->default('all')->comment('all, customers, staff, admins');
            $table->timestamp('starts_at')->nullable()->comment('Visible from');
            $table->timestamp('ends_at')->nullable()->comment('Visible until');
            $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();
            $table->timestamps();
            $table->softDeletes();
            $table->index('status', 'idx_announcements_status');
            $table->index('type', 'idx_announcements_type');
            $table->index('visible_to', 'idx_announcements_visible_to');
            $table->index('starts_at', 'idx_announcements_starts_at');
            $table->index('ends_at', 'idx_announcements_ends_at');
            $table->comment('Stores announcements and maintenance notices');
        });

        Schema::create('activity_logs', function (Blueprint $table) {
            $table->id();
            $table->foreignId('user_id')->nullable()->constrained('users')->nullOnDelete();
            $table->string('action', 150)->comment('Action name');
            $table->text('description')->nullable()->comment('Human-readable activity description');
            $table->string('subject_type', 150)->nullable()->comment('Related model/table name');
            $table->unsignedBigInteger('subject_id')->nullable()->comment('Related record ID');
            $table->string('ip_address', 45)->nullable()->comment('IP address');
            $table->text('user_agent')->nullable()->comment('Browser/device user agent');
            $table->json('metadata')->nullable()->comment('Extra data in JSON');
            $table->timestamps();
            $table->index('user_id', 'idx_activity_logs_user_id');
            $table->index('action', 'idx_activity_logs_action');
            $table->index(['subject_type', 'subject_id'], 'idx_activity_logs_subject');
            $table->comment('Stores system activity logs');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('activity_logs');
        Schema::dropIfExists('announcements');
        Schema::dropIfExists('support_ticket_messages');
        Schema::dropIfExists('support_tickets');
        Schema::dropIfExists('admin_tasks');
        Schema::dropIfExists('otp_requests');
        Schema::dropIfExists('device_reset_requests');
        Schema::dropIfExists('user_tool_devices');
        Schema::dropIfExists('user_tool_accesses');
        Schema::dropIfExists('payments');
        Schema::dropIfExists('order_custom_field_values');
        Schema::dropIfExists('orders');
        Schema::dropIfExists('package_custom_fields');
        Schema::dropIfExists('package_tools');
        Schema::dropIfExists('packages');
        Schema::dropIfExists('tool_accounts');
        Schema::dropIfExists('tools');
        Schema::dropIfExists('tool_categories');
        Schema::dropIfExists('users');
    }
};
